image: registry.gitlab.com/catie_6tron/ci-template

compile:
  script:
    - python .gitlab-ci/deploy.py
    - pip install -r mbed-os/requirements.txt
    - export MBED_GCC_ARM_PATH="/opt/gcc-arm-none-eabi-6-2017-q2-update/bin/"
    - python .gitlab-ci/compile.py

  artifacts:
    name: "$CI_PROJECT_NAME"
    paths:
      - BUILD/*/GCC_ARM/*.bin
    expire_in: 1 week

  only:
    - master
    - schedules
