image: ubuntu:16.04-1

compile:
  before_script:
    - add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
    - apt-get update
    - apt-get install -y gcc-arm-embedded

  script:
    - sed -i -e "s/gitlab.com/gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/g" *.lib
    - if [ -d "mbed-os" ];then  cd mbed-os/; git remote set-url origin https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/catie_6tron/mbed-os; git pull; cd ..; fi
    - mbed deploy
    - touch .mbed
    - mbed toolchain GCC_ARM
    - cat mbed-os/targets/targets.json | grep ZEST | cut -d '"' -f 2 >> targets
    - for j in $(cat targets); do mbed target $j; mbed compile; done

  only:
    - master
    - schedules
